### ISSUE TITLE
New release (after the pinned issues!): graduating from toy to product

### ISSUE THREAD

**Issue by xparq** [xparq/sfw#183]
Most importantly: 
- [x] finish xparq/sfw2#171 first, and then
- [x] also the text selection (#165)!

- [ ] The horrible font collapse problem (#196) should be done, too, but it seems "so orthogonal to everything" that the release could even go ahead with despite that... (Should then mention it in the Release Notes.)

----
After fixing 2 of the 3 most embarrassing UX bugs (1. focus loss, 2. missing onLeave events causing stuck I-beam cursor -- 3. text selection's still pending), the entire vibe of the project changes from "toy/proto" to "serious toolkit" state.

----
Note that there are other UX bugs still (e.g. xparq/sfw2#45 and xparq/sfw2#182.), but they are less embarrassing, as they are less exposed & distractive.

#### UPDATE:
- Also pinned xparq/sfw2#45 to keep an eye on it, as now there's a chance it actually got fixed by xparq/sfw#192
  _But then unpinned it, as it still wasn't quite important enough to take away that spot._

**Comment by xparq** [comment]
Add #161 (tabs in the srcs) too, preferably, to emphasize the shift even in aspects like code conventions.

**Comment by xparq** [comment]
_OK, apparently, I just couldn't do it... Very educative. I'm still not sure why (despite my moderate ADD)._

**Comment by xparq** [comment]
Didn't happen before moving the repo to sfw2, so... Closing this now is really the only way "forward"...
