### ISSUE TITLE
TODO items from a deleted comment: Rename/redesign GUI::themeChanged(); theme setters that manage notifications; custom event hooks

### ISSUE THREAD

**Issue by xparq** [xparq/sfw#420]
- [ ]			demo.themeChanged(); //!! Poorly named event broadcasting call that triggers onThemeChanged callbacks.

- [ ]			//!!?? Sync (reset) the wallpaper alpha slider:
			//!! This could also be done (in the future) via a "custom override" of the onThemeChanged() callback
			//!! (without actually deriving a widget and all the depressing C++ hurdles it'd entail), e.g. with
			//!! the upcoming API of `on()`: slider->on(ThemeChanged, [](auto* w) { w->set(Theme::bgColor.a()); });
			//!! and then the broadcast here could be enonugh.
			//demo.update<Slider>("Wallpaper α", Theme::bgColor.a());
- [ ]			//!! Also, theme prop. changes would go thru method calls, and they'd automatically create ThemeChanged events!
